apiVersion: v1
kind: Service
metadata:
  name: app-demdxx
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: app-demdxx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demdxx
spec:
  selector:
    matchLabels:
      app: app-demdxx
  replicas: 1
  template:
    metadata:
      labels:
        app: app-demdxx
    spec:
      containers:
      - name: app-demdxx
        image: registry.geniusrabbit.dev/demdxx/www:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "16Mi"
            cpu: "50m"
          limits:
            memory: "32Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: registry-access
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-demdxx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: demdxx.com
    http:
      paths:
      - backend:
          serviceName: app-demdxx
          servicePort: 80